spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


  datasource:
    url: jdbc:mysql://127.0.0.1:3307/demo?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root

    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      max-active: 3
      initial-size: 1

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 1234

